uploads = []
generated = []

[[outputs]]
id = "KHeVUdqnRXAgDBRcXR3cC"
uri = "file://DualVisionAI_v1.0.0.tar.gz"
type = "unspecified"
title = "DualVision AI Detector — YOLO12 + Icon + Exit Button Fix"
